### ISSUE TITLE
Errors when running redpanda benchmark tests

### ISSUE THREAD

**Issue by sparrowV** [redpanda-data/openmessaging-benchmark#16]
Greetings,
Im running redpanda locally on ubuntu via docker. I tried to run benchmark tests via the command:
`  sudo bin/benchmark -d driver-redpanda/redpanda-ack-all-group-linger-10ms.yaml \
 	workloads/blog/1-topic-100-partitions-1kb-4-producers-500k-rate.yaml`
I just changed partition count to 1, since I only have one node/broker. 

I have few issues. Would be great if you can point me to right direction.

1)
After running the command, I see this kind of errors:
![error](https://user-images.githubusercontent.com/29176362/176117061-9a745750-6dd9-4822-83d3-be4a28395237.png)

What might be causing this indexOutOfBoundException and how can I fix it?
2)
I see these kind of stats being printed periodically. What should be the final outcome of the test? 
![stats2](https://user-images.githubusercontent.com/29176362/176117531-f5ee32a8-eaaa-408c-a37b-98aba4862a7e.png)

3) I set 1 min to test duration, but it does not finish at all. I see bunch of errors that I mentioned above. Can it be a reason why the test does not finish?

@rkruze Can  you share your thoughs about it?

**Comment by esteban** [comment]
@sparrowV can you try to rebuild OMB but bumping the HdrHistogram version to 2.1.12? my hunch is that you are running into 2 issues from HdrHistogram:
1.

**Comment by esteban** [comment]
In fact, seems that commit didn't go into 2.1.12 but it stills on the dev branch. Can you please confirm what version of JDK are you using? Also, that error just be due how HdrHistogram adjusts the buckets for generating the histograms and OMB shouldn't be failing. Also regarding to the other 2 questions, yes it will print periodically the latencies until completion of the benchmark. If the benchmark is not finishing after 1 minute, OMB might still have some pending operations and is hanging there to complete. Can you try a smaller run instead? perhaps your environment is resource constrained and it is struggling to complete.

**Comment by sparrowV** [comment]
@esteban  thanks for taking a look. I used java 17 and reduced the payload size. The tests finished successfully and generated final output json file. Thanks again
