### ISSUE TITLE
All topics are deleted by default

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/openmessaging-benchmark#29]
`result` is true by default, and this causes all topics to be deleted (not just topics created by this tool). It would be better if only topics that were created by this tool were deleted.

A few snippets where a change would be required:
https://github.com/redpanda-data/openmessaging-benchmark/blob/main/driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java#L91-L102
https://github.com/redpanda-data/openmessaging-benchmark/blob/main/driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java#L91-L101

**Comment by hcoyote** [comment]
Believe this has been resolved with @tmgstevens changes to limit deletion to just the topics matching a particular string used with benchmarking.

**Comment by hcoyote** [comment]
https://github.com/redpanda-data/openmessaging-benchmark/pull/58
