### ISSUE TITLE
Ansible galaxy node exporter download fails intermittantly

### ISSUE THREAD

**Issue by WesWWagner** [redpanda-data/openmessaging-benchmark#72]
This issue crops up quite regularly on larger build out. The work around is to rerun. We should consider some internal retries.

TASK [geerlingguy.node_exporter : Download and unarchive node_exporter into temporary location.] ***********************************************************************************************************************
fatal: [35.247.77.147]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz, Request failed: <urlopen error [Errno 104] Connection reset by peer>"}
fatal: [35.247.13.169]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz, Request failed: <urlopen error [Errno 104] Connection reset by peer>"}
changed: [35.247.15.158]
changed: [34.82.201.249]
changed: [34.127.49.156]
fatal: [34.127.124.253]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz, Request failed: <urlopen error [Errno 104] Connection reset by peer>"}
changed: [35.233.238.241]
changed: [34.145.49.5]
changed: [35.230.12.29]
changed: [34.82.118.174]
changed: [35.230.87.240]

**Comment by hcoyote** [comment]
This is more likely related to github rate limits or connection issues between the node(s) running the download and github. we've run into the rate limit issue before when running repeated updates frequently. github download and api operations are pretty low for unauthenticated requests.

Not sure there's anything we can do to get a third party module to retry. If it happens again, I'd recommend trying to curl that file manually with some debug enabled and grab the output for additional review.
